# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xczu7ev-ffvf1517-1LV-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.cache/wt [current_project]
set_property parent.project_path C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/multiplier/a_generator.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/alu.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/alu_out_selector.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/beh_adder.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/multiplier/booth_encoder.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/1_if/btb/btb.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/fun/fun_pack_adder.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/carry_generator.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/carry_select_block.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/comparator.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/cu/control_words.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/cu/func_words.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/cu/opcodes.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/cu/cu.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/datapath.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/equality_comparator.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/ex_mem_reg.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/ex_stage.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/f_id_reg.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/fa.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/g_unit.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/id_ex_reg.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/2_id/id_stage.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/1_if/if_stage.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/nand3.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/nand4.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/logicals/logicals.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/4_mem/mem_sign_extender.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/4_mem/mem_stage.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/mem_wb_reg.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/cu/memory_controller.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/multiplier/mul.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/mux_2x1.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/mux_4x1.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/mux_6x1.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/mux_7x1.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/mux_7x1_single_bit.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/p4_adder.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/pg_net_block.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/pg_network.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/pg_unit.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/rca_generic_struct.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/reg_en.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/2_id/rf.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/misc/rshift_reg.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/shifter/stype.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/shifter/shifter_t2.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/2_id/sign_extender.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/cu/stall_unit.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/3_ex/adder/sum_generator.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/5_wb/wb_stage.vhd
  C:/Users/Nicole/Desktop/Vivado/dlx_final/dlx_final.srcs/sources_1/imports/dlx/dlx_syn.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top dlx_syn -part xczu7ev-ffvf1517-1LV-i


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dlx_syn.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dlx_syn_utilization_synth.rpt -pb dlx_syn_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
